## create development container
# docker-compose -f dev.docker-compose.yml up -d

## log into the dev container 
# docker exec -it devenv bash

## Install packages and Start the application
# npm install
# npm start

version: '3.8'

services: 

  app:
    image: node:16
    container_name: devenv
    volumes:
        - ./:/app
        - /app/node_modules
    working_dir: /app
    ports:
        - 8090:8090
    command: bash -c "tail -f /dev/null"