version: "3"

services:
  db:
    container_name: middleware_db
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  middleware:
    container_name: middleware
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8090:8090"


volumes:
  postgres-data: