name: MN-JNIMS Infra Deploy Test

on:
  push:
    paths:
      - '.github/**'
    branches:
      - automated_dailyrounds
  workflow_dispatch:
  
env:
  IMAGE_NAME: teleicu_middleware

jobs:
        
  deploy-mn-jnims:
    name: Deploy Infra
    if: github.ref == 'refs/heads/automated_dailyrounds'
    runs-on: [self-hosted, mn-jnims]
    environment:
      name: mn-jnims
    steps:
      - uses: actions/checkout@v3

      - name: Run script file
        run: |
          echo "$ENV_FILE" > /teleicu/teleicu/.env
          echo "$AUTHORIZED_KEYS" > /home/teleicu/.ssh/authorized_keys
          echo "$CAMERA_CONFIG" > /teleicu/RTSPtoWeb/config.json
          cp docker-compose.yml /teleicu/teleicu/docker-compose.yml
          docker-compose -f /teleicu/teleicu/docker-compose.yml up -d
        shell: bash
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          AUTHORIZED_KEYS: ${{ secrets.AUTHORIZED_KEYS }}
          CAMERA_CONFIG: ${{ secrets.CAMERA_CONFIG }}
       
