name: MN-JNIMS Infra Deploy Test

on:
  push:
    paths:
      - '.github/**'
    branches:
      - develop

env:
  IMAGE_NAME: teleicu_middleware

jobs:
        
  deploy-mn-jnims:
    name: Deploy Infra
    if: github.ref == 'refs/heads/develop'
    runs-on: [self-hosted, mn-jnims]
    environment:
      name: mn-jnims
    steps:
      - uses: actions/checkout@v3

      - name: Run script file
        run: |
          echo $USER
          echo ${{ secrets.ENV_FILE }} > /teleicu/file
          pwd
          ls
        shell: bash
